// Fallback categories for when the backend is not available
export const fallbackCategories = [
  {
    id: 'tech',
    name: 'Tecnología e Informática',
    description: 'Empleos relacionados con tecnología, desarrollo de software, sistemas y telecomunicaciones',
    parentId: null,
    path: ['Tecnología e Informática'],
    pathString: 'Tecnología e Informática',
    level: 0,
    isActive: true,
    displayOrder: 0,
    childCount: 10,
    vacancyCount: 0,
    totalVacancyCount: 150,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-dev',
    name: 'Desarrollo de Software',
    description: 'Programación, desarrollo web, móvil y de aplicaciones',
    parentId: 'tech',
    path: ['Tecnología e Informática', 'Desarrollo de Software'],
    pathString: 'Tecnología e Informática.Desarrollo de Software',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 45,
    totalVacancyCount: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'tech-ai',
    name: 'Inteligencia Artificial',
    description: 'Machine Learning, Data Science y AI',
    parentId: 'tech',
    path: ['Tecnología e Informática', 'Inteligencia Artificial'],
    pathString: 'Tecnología e Informática.Inteligencia Artificial',
    level: 1,
    isActive: true,
    displayOrder: 1,
    childCount: 0,
    vacancyCount: 25,
    totalVacancyCount: 25,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sales',
    name: 'Ventas y Comercial',
    description: 'Empleos en ventas, atención al cliente y desarrollo comercial',
    parentId: null,
    path: ['Ventas y Comercial'],
    pathString: 'Ventas y Comercial',
    level: 0,
    isActive: true,
    displayOrder: 1,
    childCount: 8,
    vacancyCount: 0,
    totalVacancyCount: 200,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sales-direct',
    name: 'Ventas Directas',
    description: 'Vendedores, ejecutivos de ventas y representantes comerciales',
    parentId: 'sales',
    path: ['Ventas y Comercial', 'Ventas Directas'],
    pathString: 'Ventas y Comercial.Ventas Directas',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 80,
    totalVacancyCount: 80,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sales-retail',
    name: 'Retail',
    description: 'Ventas en tiendas, supermercados y centros comerciales',
    parentId: 'sales',
    path: ['Ventas y Comercial', 'Retail'],
    pathString: 'Ventas y Comercial.Retail',
    level: 1,
    isActive: true,
    displayOrder: 1,
    childCount: 0,
    vacancyCount: 120,
    totalVacancyCount: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'admin',
    name: 'Administración y Finanzas',
    description: 'Empleos en administración, contabilidad, finanzas y recursos humanos',
    parentId: null,
    path: ['Administración y Finanzas'],
    pathString: 'Administración y Finanzas',
    level: 0,
    isActive: true,
    displayOrder: 2,
    childCount: 8,
    vacancyCount: 0,
    totalVacancyCount: 180,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'admin-accounting',
    name: 'Contabilidad',
    description: 'Contadores, auditores y asistentes contables',
    parentId: 'admin',
    path: ['Administración y Finanzas', 'Contabilidad'],
    pathString: 'Administración y Finanzas.Contabilidad',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 60,
    totalVacancyCount: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'admin-hr',
    name: 'Recursos Humanos',
    description: 'Reclutamiento, capacitación y gestión de personal',
    parentId: 'admin',
    path: ['Administración y Finanzas', 'Recursos Humanos'],
    pathString: 'Administración y Finanzas.Recursos Humanos',
    level: 1,
    isActive: true,
    displayOrder: 1,
    childCount: 0,
    vacancyCount: 40,
    totalVacancyCount: 40,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'health',
    name: 'Salud y Medicina',
    description: 'Empleos en el sector salud, medicina y cuidado de personas',
    parentId: null,
    path: ['Salud y Medicina'],
    pathString: 'Salud y Medicina',
    level: 0,
    isActive: true,
    displayOrder: 3,
    childCount: 8,
    vacancyCount: 0,
    totalVacancyCount: 120,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'health-nursing',
    name: 'Enfermería',
    description: 'Enfermeros, técnicos en enfermería y auxiliares',
    parentId: 'health',
    path: ['Salud y Medicina', 'Enfermería'],
    pathString: 'Salud y Medicina.Enfermería',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 50,
    totalVacancyCount: 50,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'education',
    name: 'Educación y Capacitación',
    description: 'Empleos en educación, enseñanza y formación',
    parentId: null,
    path: ['Educación y Capacitación'],
    pathString: 'Educación y Capacitación',
    level: 0,
    isActive: true,
    displayOrder: 4,
    childCount: 7,
    vacancyCount: 0,
    totalVacancyCount: 90,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'construction',
    name: 'Construcción y Arquitectura',
    description: 'Empleos en construcción, arquitectura e ingeniería civil',
    parentId: null,
    path: ['Construcción y Arquitectura'],
    pathString: 'Construcción y Arquitectura',
    level: 0,
    isActive: true,
    displayOrder: 5,
    childCount: 8,
    vacancyCount: 0,
    totalVacancyCount: 160,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'construction-civil',
    name: 'Construcción Civil',
    description: 'Maestros, operarios y técnicos en construcción',
    parentId: 'construction',
    path: ['Construcción y Arquitectura', 'Construcción Civil'],
    pathString: 'Construcción y Arquitectura.Construcción Civil',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 100,
    totalVacancyCount: 100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gastronomy',
    name: 'Gastronomía y Turismo',
    description: 'Empleos en restaurantes, hoteles, turismo y servicios gastronómicos',
    parentId: null,
    path: ['Gastronomía y Turismo'],
    pathString: 'Gastronomía y Turismo',
    level: 0,
    isActive: true,
    displayOrder: 6,
    childCount: 7,
    vacancyCount: 0,
    totalVacancyCount: 140,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gastronomy-kitchen',
    name: 'Cocina',
    description: 'Chefs, cocineros y ayudantes de cocina',
    parentId: 'gastronomy',
    path: ['Gastronomía y Turismo', 'Cocina'],
    pathString: 'Gastronomía y Turismo.Cocina',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 70,
    totalVacancyCount: 70,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'transport',
    name: 'Transporte y Logística',
    description: 'Empleos en transporte, distribución y logística',
    parentId: null,
    path: ['Transporte y Logística'],
    pathString: 'Transporte y Logística',
    level: 0,
    isActive: true,
    displayOrder: 7,
    childCount: 7,
    vacancyCount: 0,
    totalVacancyCount: 110,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'transport-driving',
    name: 'Conducción',
    description: 'Conductores de camión, bus y vehículos livianos',
    parentId: 'transport',
    path: ['Transporte y Logística', 'Conducción'],
    pathString: 'Transporte y Logística.Conducción',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 60,
    totalVacancyCount: 60,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'marketing',
    name: 'Marketing y Comunicaciones',
    description: 'Empleos en marketing, publicidad, comunicaciones y medios',
    parentId: null,
    path: ['Marketing y Comunicaciones'],
    pathString: 'Marketing y Comunicaciones',
    level: 0,
    isActive: true,
    displayOrder: 8,
    childCount: 7,
    vacancyCount: 0,
    totalVacancyCount: 85,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'marketing-digital',
    name: 'Marketing Digital',
    description: 'Community managers, SEO y SEM',
    parentId: 'marketing',
    path: ['Marketing y Comunicaciones', 'Marketing Digital'],
    pathString: 'Marketing y Comunicaciones.Marketing Digital',
    level: 1,
    isActive: true,
    displayOrder: 0,
    childCount: 0,
    vacancyCount: 35,
    totalVacancyCount: 35,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];

export const fallbackCategoryTree = [
  {
    category: fallbackCategories[0], // Tecnología e Informática
    children: [
      { category: fallbackCategories[1], children: [], vacancyCount: 45 }, // Desarrollo de Software
      { category: fallbackCategories[2], children: [], vacancyCount: 25 }, // Inteligencia Artificial
    ],
    vacancyCount: 150,
  },
  {
    category: fallbackCategories[3], // Ventas y Comercial
    children: [
      { category: fallbackCategories[4], children: [], vacancyCount: 80 }, // Ventas Directas
      { category: fallbackCategories[5], children: [], vacancyCount: 120 }, // Retail
    ],
    vacancyCount: 200,
  },
  {
    category: fallbackCategories[6], // Administración y Finanzas
    children: [
      { category: fallbackCategories[7], children: [], vacancyCount: 60 }, // Contabilidad
      { category: fallbackCategories[8], children: [], vacancyCount: 40 }, // Recursos Humanos
    ],
    vacancyCount: 180,
  },
  {
    category: fallbackCategories[9], // Salud y Medicina
    children: [
      { category: fallbackCategories[10], children: [], vacancyCount: 50 }, // Enfermería
    ],
    vacancyCount: 120,
  },
  {
    category: fallbackCategories[11], // Educación y Capacitación
    children: [],
    vacancyCount: 90,
  },
  {
    category: fallbackCategories[12], // Construcción y Arquitectura
    children: [
      { category: fallbackCategories[13], children: [], vacancyCount: 100 }, // Construcción Civil
    ],
    vacancyCount: 160,
  },
  {
    category: fallbackCategories[14], // Gastronomía y Turismo
    children: [
      { category: fallbackCategories[15], children: [], vacancyCount: 70 }, // Cocina
    ],
    vacancyCount: 140,
  },
  {
    category: fallbackCategories[16], // Transporte y Logística
    children: [
      { category: fallbackCategories[17], children: [], vacancyCount: 60 }, // Conducción
    ],
    vacancyCount: 110,
  },
  {
    category: fallbackCategories[18], // Marketing y Comunicaciones
    children: [
      { category: fallbackCategories[19], children: [], vacancyCount: 35 }, // Marketing Digital
    ],
    vacancyCount: 85,
  },
];